## Numpy Array Operations


In [1]:
import numpy as np

In [5]:
arr = np.arange(1 , 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# Basic Slicing

print("Basic Slicing " , arr[2:7])

Basic Slicing  [3 4 5 6 7]


In [ ]:
#With steps

print("With Step Slicing " , arr[1:8 :2])  #every second position

With Step Slicing  [2 4 6 8]


In [8]:
#Negative indexing


print("negative indexing " , arr[-3])

negative indexing  8


### with 2D arrays

In [14]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])

print("Specific Element :" , arr_2d[1,2])
print("Entire Row :" , arr_2d[1])
print("Entire Col :" , arr_2d[:,1])

Specific Element : 6
Entire Row : [4 5 6]
Entire Col : [2 5 8]


### Sorting

In [15]:
unsorted = np.array([3,1,4,9,2,5,8,6])
print("Sorted array " , np.sort(unsorted))

Sorted array  [1 2 3 4 5 6 8 9]


In [17]:
arr_2d_unsorted = np.array([
    [3,1],
    [1,2],
    [2,3]
])
print("Sorted 2D by column ", np.sort(arr_2d_unsorted , axis=0))
print("Sorted 2D by row ", np.sort(arr_2d_unsorted , axis=1))

Sorted 2D by column  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D by row  [[1 3]
 [1 2]
 [2 3]]


## Filter

In [21]:
numbers = np.arange(1,11)
even_no = numbers[numbers % 2 == 0]
print("even no " , even_no)

even no  [ 2  4  6  8 10]


## Filter with Mask

In [23]:
mask = numbers  > 5
print("Num greater then 5 " ,  numbers[mask])

Num greater then 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [28]:
print(numbers)

indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print('Numbers where', numbers[where_result])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5]
Numbers where [ 6  7  8  9 10]


In [ ]:
conditon_array = np.where(numbers > 5 , numbers * 2 , numbers)   #just like if else
print("condition array : " , conditon_array)

condition array :  [ 1  2  3  4  5 12 14 16 18 20]


In [30]:
conditon_array = np.where(numbers > 5 ,  "true" , "false")   #just like if else
print("condition array : " , conditon_array)

condition array :  ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [31]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#combined = arr1 + arr2  # this adds the elements


combined = np.concatenate((arr1 , arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility shape ", a.shape == b.shape)

Compatibility shape  False


In [34]:
orignal = np.array([[1,2] , [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((orignal , new_row))    #vstack hamesha row add karne ke lie use hta he
print(with_new_row)

[[1 2]
 [3 4]
 [5 6]]


In [36]:
new_col = np.array([[7] , [8]])
with_new_col = np.hstack((orignal , new_col))
print(with_new_col)

[[1 2 7]
 [3 4 8]]


### Delete

In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9])
deleted = np.delete(arr , 2)
print(deleted)

[1 2 4 5 6 7 8 9]
