## Numpy array and basics

In [3]:
import numpy as np

creating array from lists

In [4]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [8]:
#arr_2d = np.array([1,2,3] , [4,5,6]) #this is a error because it should contain single list here we provide 2


#correct v of this
arr_2d = np.array([[1,2,3] , [4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

### List vs Numpy array

In [9]:
py_list = [1,2,3]
print('Python list multiplication : ' , py_list * 2)


np_array = np.array([1,2,3])
print('Python array multiplication : ' , np_array * 2)


Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]


### creating array from scratch

In [13]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# array of constants

full = np.full((2,3) , 7)
full

array([[7, 7, 7],
       [7, 7, 7]])

In [17]:
#array of random num

random = np.random.random((2,3))  #here is a random is a class and other random is a method inside the random class
random

array([[0.01254462, 0.02844168, 0.10830264],
       [0.77536219, 0.67157313, 0.08648773]])

In [ ]:
# array of sequence

sequence = np.arange(0 , 10 ,2)   
sequence

array([0, 2, 4, 6, 8])

### Vector, Matrix and Tensor

In [19]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [ ]:
matrix = np.array([[1,2,3],      #matrix is always 2D
                   [4,5,6]
                  ])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
tesnor = np.array([
            [[1,2] , [3,4]],    # tensor is used for more dimensions
            [[5,6] , [7,8]]                   
                ])

tesnor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Array Properties

In [23]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print("Shape :" , arr.shape)
print("Dimensions :" , arr.ndim)
print("Size :" , arr.size)
print("Dtype :" , arr.dtype)

Shape : (2, 3)
Dimensions : 2
Size : 6
Dtype : int64


### Array reShaping

In [25]:
arr = np.arange(12)
print("Orignal array :" , arr)

Orignal array : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
reshaped = arr.reshape((3,4))
print("Reshaped array :" , reshaped)

Reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
flattened = reshaped.flatten()
print("Flatten array :" , flattened)

Flatten array : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Above all methods returned the copy of orignal array

# but ravel method returns the orignal array

In [ ]:
raveled = reshaped.ravel()      
print("Raveled array :" , raveled)  

Raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
#Transpose 

transpose = reshaped.T
print("Transpose array :" , transpose)

Transpose array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [1]:
print("Hello")

Hello
