## Numpy array and basics

In [3]:
import numpy as np

creating array from lists

In [4]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [8]:
#arr_2d = np.array([1,2,3] , [4,5,6]) #this is a error because it should contain single list here we provide 2


#correct v of this
arr_2d = np.array([[1,2,3] , [4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

### List vs Numpy array

In [9]:
py_list = [1,2,3]
print('Python list multiplication : ' , py_list * 2)


np_array = np.array([1,2,3])
print('Python array multiplication : ' , np_array * 2)


Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]


### creating array from scratch

In [13]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# array of constants

full = np.full((2,3) , 7)
full

array([[7, 7, 7],
       [7, 7, 7]])

In [17]:
#array of random num

random = np.random.random((2,3))  #here is a random is a class and other random is a method inside the random class
random

array([[0.01254462, 0.02844168, 0.10830264],
       [0.77536219, 0.67157313, 0.08648773]])

In [ ]:
# array of sequence

sequence = np.arange(0 , 10 ,2)   
sequence

array([0, 2, 4, 6, 8])