In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [2]:
digits = load_digits()

In [4]:
X_train , X_test , y_train , y_test = train_test_split(digits.data ,  digits.target , test_size = 0.3)

In [5]:
lr = LogisticRegression()
lr.fit(X_train , y_train)
lr.score(X_test , y_test)

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [6]:
svm = SVC()
svm.fit(X_train , y_train)
svm.score(X_test , y_test)

0.9777777777777777

In [7]:
rf = RandomForestClassifier()
rf.fit(X_train , y_train)
rf.score(X_test , y_test)

0.9666666666666667

In [8]:
# ab hm ne 3 aleda models laga kar prediction chk ki lakin ab agar hm same cheez ko dobara run karte to results thore differnt hte asa kio he samples put in x and y train test get changed so it is not recomended to run the train test split only one time we have to run it multiple times

K-fold

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model , X_train , X_test , y_train , y_test):
    model.fit(X_train , y_train)
    return model.score(X_test , y_test)

In [14]:
get_score(LogisticRegression() , X_train , X_test , y_train , y_test)

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [15]:
get_score(SVC() , X_train , X_test , y_train , y_test)

0.9777777777777777

In [16]:
get_score(RandomForestClassifier() , X_train , X_test , y_train , y_test)

0.9592592592592593

In [17]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [ ]:
# actually we dont have to manually write the below code k fold


In [20]:
scores_lr = []
scores_svm = []
scores_rf = []


for train_index , test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    scores_lr.append(get_score(LogisticRegression() , X_train , X_test , y_train , y_test ))
    scores_rf.append(get_score(RandomForestClassifier() , X_train , X_test , y_train , y_test))
    scores_svm.append(get_score(SVC() , X_train , X_test , y_train , y_test))


c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/

In [21]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [22]:
scores_rf

[0.9282136894824707, 0.9616026711185309, 0.9248747913188647]

In [23]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [24]:
# already methods are made just we have to use it

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score(LogisticRegression() , digits.data  ,digits.target)

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC() , digits.data  ,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [29]:
cross_val_score(RandomForestClassifier(n_estimators=40) , digits.data  ,digits.target)

array([0.93888889, 0.89722222, 0.95264624, 0.95821727, 0.9275766 ])

In [30]:
cross_val_score(RandomForestClassifier(n_estimators=5) , digits.data  ,digits.target)

array([0.88888889, 0.8       , 0.88579387, 0.92479109, 0.85236769])